import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children} </body>
    </html>
  );
}
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import ReactLenis from "lenis/react";

// const ppneuemontreal = localFont({
//   src: [
//     {
//       path: "./font/ppneuemontreal-medium.otf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./font/ppneuemontreal-bold.otf",
//       weight: "800",
//       style: "bold",
//     },
//   ],
//   variable: "--font-ppneuemontreal",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${ppneuemontreal.variable} bg-black text-white antialiased font-ppneuemontreal`}
//       >
//         <ReactLenis root>{children}</ReactLenis>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import "./globals.css";
// import { Kaisei_Tokumin } from "next/font/google";

// const KaiseiTokumin = Kaisei_Tokumin({
//   weight: ["400", "500", "700", "800"],
//   subsets: ["latin"],
//   variable: "--font-kaisei",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${KaiseiTokumin.variable} antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }
