import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppneuemontreal = localFont({
  src: [
    {
      path: "./font/ppneuemontreal-medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/ppneuemontreal-bold.otf",
      weight: "800",
      style: "bold",
    },
  ],
  variable: "--font-ppneuemontreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppneuemontreal.variable} antialiased font-ppneuemontreal`}
      >
        {children}
      </body>
    </html>
  );
}
